## 파이썬 머신러닝/딥러닝 주요 생태계 라이브러리 정리
- 딥러닝 : Tensorflow, Keras, Pytorch
- 머신러닝 : Scikit-learn
- 선형대수, 통계 : Numpy, SciPy, Math
- 데이터 핸들링 : Pandas
- 시각화 : Matplotlib, Seaborn, Plotly
- 대화형 파이썬 툴 : Jupyter(notebook, lab)

## Numpy
- 기반 데이터 타입 : ndarray
- 다차원 배열을 쉽게 생성하고 다양한 연산을 수행하는데 용이
- ndarray내의 데이터 값은 숫자, 문자, bool값 모두 가능
    - 특성상 같은 타입의 데이터만 들어갈 수 있다
    - 속 안에 있는 데이터 타입은 `.dtype`을 이용해 확인 가능하다
    - 타입변환의 경우는 `astype()`함수를 통해 수행할 수 있다

`array()`: list 또는 nested list를 인자로 받아 ndarray로 변환하는 함수
- type() : ndarray 클래스 반환
- .shape : ndarray 형태 반환
- .ndim : ndarray 차원반환

In [7]:
import numpy as np

# 1차원 ndarray
array1 = np.array([1,2,3])
print('array1 type:',type(array1))
print('array1 array 형태:',array1.shape)
print('array1 array 차원:',array1.ndim)

# 2차원 ndarray (주의!)
array2 = np.array([[1,2,3]])
print('array2 type:',type(array2))
print('array2 array 형태:',array2.shape)
print('array2 array 차원:',array2.ndim)


# 2차원 ndarray
array3 = np.array([[1,2,3],
                  [2,3,4]])
print('array3 type:',type(array3))
print('array3 array 형태:',array3.shape)
print('array3 array 차원:',array3.ndim)


array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array1 array 차원: 1
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (1, 3)
array2 array 차원: 2
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (2, 3)
array3 array 차원: 2


**ndarray axis 기반의 연산 수행**
- 수업이 많은 시간을 들여 혼자 고민한 결과 다음과 같이 axis와 numpy 차원을 연상할 수 있는 좋은 방법이 떠올라서 공유해보려고 한다.
- 고등학교 수학에서 배운, x, y, z 좌표계를 생각해보자.
- Numpy에서는 x축은 0축, y축은 1축, z축은 2축이라고 한다. (아래 그림 참고)
- 밑에서 소개하는 각각의 array1, array2, array3 은 1차원, 2차원, 3차원 Ndarray이고 이를 좌표계에 투영시킨 그림이다.

<img src="img/numpy_dimension.jpg" width="700">

In [25]:
array1 = np.array([1,2,3])
print(array1)
print("형태:", array1.shape)
print("전체 :", array1.sum())
print("행기준 :", array1.sum(axis=0)) # 행 기반 연산

[1 2 3]
형태: (3,)
전체 : 6
행기준 : 6


In [64]:
array2 = np.array([[1,2],
                  [3,4]])
print(array2)
print("형태:", array2.shape)
print("전체 :", array2.sum())
print("행기준 :", array2.sum(axis=0)) # 행 기반 연산
print("열기준 :", array2.sum(axis=1)) # 열 기반 연산

[[1 2]
 [3 4]]
형태: (2, 2)
전체 : 10
행기준 : [4 6]
열기준 : [3 7]


In [63]:
array3 = np.array(range(1,9)).reshape([2,2,2])

print(array3)
print("형태:", array3.shape)
print("전체 :", array3.sum())
print("X축기준 :", array3.sum(axis=0)) # axis=0 기반 연산
print("Y축기준 :", array3.sum(axis=1)) # axis=1 기반 연산
print("Z축기준 :", array3.sum(axis=2)) # axis=2 기반 연산

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
형태: (2, 2, 2)
전체 : 36
X축기준 : [[ 6  8]
 [10 12]]
Y축기준 : [[ 4  6]
 [12 14]]
Z축기준 : [[ 3  7]
 [11 15]]
